# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35ea84f3b843fc5f6b7be1c156ecbe9b947eaf2a27b109f886c6d808647a2ae92d20d9f9939c193a5b349a15f9ac3acd1da7f181c7b1f65dbffbfa2cd0adc55

test:
  secret_key_base: 68eabb3f66b2384021a5fb00417fbc5c74046b11d15ec9821ce417436cae032c62020f2bf7e046b09d14610f3e843e979a312b178db5142579476e3e1a786844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
